/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as PackersAndMoversCityRouteImport } from './routes/packers-and-movers.$city'
import { Route as HaridwarToDestinationRouteImport } from './routes/haridwar-to.$destination'
import { Route as FeedbackCodeRouteImport } from './routes/feedback.$code'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const PackersAndMoversCityRoute = PackersAndMoversCityRouteImport.update({
  id: '/packers-and-movers/$city',
  path: '/packers-and-movers/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const HaridwarToDestinationRoute = HaridwarToDestinationRouteImport.update({
  id: '/haridwar-to/$destination',
  path: '/haridwar-to/$destination',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackCodeRoute = FeedbackCodeRouteImport.update({
  id: '/feedback/$code',
  path: '/feedback/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/enquiry': typeof EnquiryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/feedback/$code': typeof FeedbackCodeRoute
  '/haridwar-to/$destination': typeof HaridwarToDestinationRoute
  '/packers-and-movers/$city': typeof PackersAndMoversCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/enquiry': typeof EnquiryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/feedback/$code': typeof FeedbackCodeRoute
  '/haridwar-to/$destination': typeof HaridwarToDestinationRoute
  '/packers-and-movers/$city': typeof PackersAndMoversCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/enquiry': typeof EnquiryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/feedback/$code': typeof FeedbackCodeRoute
  '/haridwar-to/$destination': typeof HaridwarToDestinationRoute
  '/packers-and-movers/$city': typeof PackersAndMoversCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/enquiry'
    | '/sitemap.xml'
    | '/track'
    | '/admin'
    | '/blog/$slug'
    | '/feedback/$code'
    | '/haridwar-to/$destination'
    | '/packers-and-movers/$city'
    | '/services/$service'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/enquiry'
    | '/sitemap.xml'
    | '/track'
    | '/admin'
    | '/blog/$slug'
    | '/feedback/$code'
    | '/haridwar-to/$destination'
    | '/packers-and-movers/$city'
    | '/services/$service'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/enquiry'
    | '/sitemap.xml'
    | '/track'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/feedback/$code'
    | '/haridwar-to/$destination'
    | '/packers-and-movers/$city'
    | '/services/$service'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EnquiryRoute: typeof EnquiryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeedbackCodeRoute: typeof FeedbackCodeRoute
  HaridwarToDestinationRoute: typeof HaridwarToDestinationRoute
  PackersAndMoversCityRoute: typeof PackersAndMoversCityRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packers-and-movers/$city': {
      id: '/packers-and-movers/$city'
      path: '/packers-and-movers/$city'
      fullPath: '/packers-and-movers/$city'
      preLoaderRoute: typeof PackersAndMoversCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haridwar-to/$destination': {
      id: '/haridwar-to/$destination'
      path: '/haridwar-to/$destination'
      fullPath: '/haridwar-to/$destination'
      preLoaderRoute: typeof HaridwarToDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$code': {
      id: '/feedback/$code'
      path: '/feedback/$code'
      fullPath: '/feedback/$code'
      preLoaderRoute: typeof FeedbackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EnquiryRoute: EnquiryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeedbackCodeRoute: FeedbackCodeRoute,
  HaridwarToDestinationRoute: HaridwarToDestinationRoute,
  PackersAndMoversCityRoute: PackersAndMoversCityRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
